# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 295bd0943750688dcd4ee2e526b02ad2bbfd7f17331e7bc2c6e15d9376e8102ff087d1c02210f8970412b530209bfb62d9fc6082880df1f8ce6a74fadf5fbda2

test:
  secret_key_base: c8f470113ab9d1b716010221eb7afea095173a30a6397d8355350868ee74d0cd6113ba65caecf7d00e6fccb62c6d46440b356e711b8d25647c670eceb71f1e0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
